#![allow(non_upper_case_globals)]

use num_enum::TryFromPrimitive;
use strum_macros::{Display, EnumString};

#[derive(Debug, Clone)]
pub struct Attributes {
    pub name: String,
    pub index: u8,
    pub air_jumps: u8,
    pub friction: f32,
    pub size: u8,
    pub gravity: f32,
    pub terminal_velocity: f32,
    pub max_walk_speed: f32,
    pub fast_fall_speed: f32,
    pub air_speed: f32,
    pub air_friction: f32,
    pub air_mobility: f32,
    pub dj_x_speed: f32,
    pub fh_jump_force: f32,
    pub sh_jump_force: f32,
    pub dj_jump_force: f32,
    pub weight: u32,
}

#[derive(Debug, Clone, EnumString, Display, PartialEq, TryFromPrimitive)]
#[repr(usize)]
pub enum Character {
    Mario,
    Fox,
    Falcon,
    DK,
    Kirby,
    Bowser,
    Link,
    Sheik,
    Ness,
    Peach,
    Popo,
    Nana,
    Pikachu,
    Samus,
    Yoshi,
    Jiggs,
    Mewtwo,
    Luigi,
    Marth,
    Zelda,
    Ylink,
    Doc,
    Falco,
    Pichu,
    GNW,
    Ganondorf,
    Roy,
}

impl Character {
    // these are all objects rather than a lookup table because it allows for customizing the characters and having
    // several unique instances of the same character with different stats. That can be useful for creating balance
    // mods, swapping to PAL values, or demonstrating a specific threshold
    pub fn get_stats(&self) -> Attributes {
        match *self {
            Character::Fox => Attributes {
                name: "Fox".to_owned(),
                index: 1,
                air_jumps: 1,
                friction: 0.08,
                size: 11,
                gravity: 0.0,
                terminal_velocity: 0.23,
                max_walk_speed: 2.8,
                fast_fall_speed: 3.4,
                air_speed: 0.83,
                air_friction: 0.02,
                air_mobility: 0.08,
                dj_x_speed: 0.88,
                fh_jump_force: 3.68,
                sh_jump_force: 2.1,
                dj_jump_force: 4.19,
                weight: 75,
            },
            Character::Marth => Attributes {
                name: "Marth".to_owned(),
                index: 18,
                air_jumps: 1,
                friction: 0.06,
                size: 14,
                gravity: 0.09,
                terminal_velocity: 2.2,
                max_walk_speed: 1.6,
                fast_fall_speed: 2.5,
                air_speed: 0.9,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 1.0,
                fh_jump_force: 2.4,
                sh_jump_force: 1.5,
                dj_jump_force: 2.03,
                weight: 87,
            },
            Character::Falcon => Attributes {
                name: "Captain Falcon".to_owned(),
                index: 2,
                air_jumps: 1,
                friction: 0.08,
                size: 14,
                gravity: 0.13,
                terminal_velocity: 2.9,
                max_walk_speed: 0.85,
                fast_fall_speed: 2.9,
                air_speed: 1.12,
                air_friction: 0.01,
                air_mobility: 0.06,
                dj_x_speed: 0.96,
                fh_jump_force: 3.1,
                sh_jump_force: 1.9,
                dj_jump_force: 2.66,
                weight: 104,
            },
            Character::Falco => Attributes {
                name: "Falco".to_owned(),
                index: 22,
                air_jumps: 1,
                friction: 0.08,
                size: 11,
                gravity: 0.17,
                terminal_velocity: 3.1,
                max_walk_speed: 1.4,
                fast_fall_speed: 3.5,
                air_speed: 0.83,
                air_friction: 0.02,
                air_mobility: 0.07,
                dj_x_speed: 0.92,
                fh_jump_force: 4.1,
                sh_jump_force: 1.9,
                dj_jump_force: 3.68,
                weight: 80,
            },
            Character::Peach => Attributes {
                name: "Peach".to_owned(),
                index: 9,
                air_jumps: 1,
                friction: 0.1,
                size: 14,
                gravity: 0.08,
                terminal_velocity: 1.5,
                max_walk_speed: 0.85,
                fast_fall_speed: 2.0,
                air_speed: 1.1,
                air_friction: 0.04,
                air_mobility: 0.07,
                dj_x_speed: 0.96,
                fh_jump_force: 2.2,
                sh_jump_force: 1.6,
                dj_jump_force: 0.0,
                weight: 90,
            },
            Character::Jiggs => Attributes {
                name: "Jigglypuff".to_owned(),
                index: 15,
                air_jumps: 5,
                friction: 0.09,
                size: 9,
                gravity: 0.06,
                terminal_velocity: 1.3,
                max_walk_speed: 0.7,
                fast_fall_speed: 1.6,
                air_speed: 1.35,
                air_friction: 0.05,
                air_mobility: 0.28,
                dj_x_speed: 0.57,
                fh_jump_force: 1.6,
                sh_jump_force: 1.05,
                dj_jump_force: 0.0,
                weight: 60,
            },
            Character::Pikachu => Attributes {
                name: "Pikachu".to_owned(),
                index: 12,
                air_jumps: 1,
                friction: 0.09,
                size: 9,
                gravity: 0.11,
                terminal_velocity: 1.9,
                max_walk_speed: 1.24,
                fast_fall_speed: 2.7,
                air_speed: 0.85,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 0.85,
                fh_jump_force: 2.6,
                sh_jump_force: 1.7,
                dj_jump_force: 2.49,
                weight: 80,
            },
            Character::Sheik => Attributes {
                name: "Sheik".to_owned(),
                index: 7,
                air_jumps: 1,
                friction: 0.08,
                size: 11,
                gravity: 0.12,
                terminal_velocity: 2.13,
                max_walk_speed: 1.2,
                fast_fall_speed: 3.0,
                air_speed: 0.8,
                air_friction: 0.04,
                air_mobility: 0.06,
                dj_x_speed: 0.96,
                fh_jump_force: 2.8,
                sh_jump_force: 2.14,
                dj_jump_force: 2.96,
                weight: 90,
            },
            Character::Samus => Attributes {
                name: "Samus".to_owned(),
                index: 13,
                air_jumps: 1,
                friction: 0.06,
                size: 14,
                gravity: 0.07,
                terminal_velocity: 1.4,
                max_walk_speed: 1.0,
                fast_fall_speed: 2.3,
                air_speed: 0.89,
                air_friction: 0.01,
                air_mobility: 0.03,
                dj_x_speed: 0.89,
                fh_jump_force: 2.1,
                sh_jump_force: 1.7,
                dj_jump_force: 2.1,
                weight: 110,
            },
            Character::Ganondorf => Attributes {
                name: "Ganondorf".to_owned(),
                index: 25,
                air_jumps: 1,
                friction: 0.07,
                size: 15,
                gravity: 0.13,
                terminal_velocity: 2.0,
                max_walk_speed: 0.73,
                fast_fall_speed: 2.6,
                air_speed: 0.78,
                air_friction: 0.02,
                air_mobility: 0.06,
                dj_x_speed: 0.98,
                fh_jump_force: 2.6,
                sh_jump_force: 2.0,
                dj_jump_force: 2.34,
                weight: 109,
            },
            Character::Roy => Attributes {
                name: "Roy".to_owned(),
                index: 26,
                air_jumps: 1,
                friction: 0.06,
                size: 14,
                gravity: 0.11,
                terminal_velocity: 2.4,
                max_walk_speed: 1.2,
                fast_fall_speed: 2.9,
                air_speed: 0.9,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 0.98,
                fh_jump_force: 2.6,
                sh_jump_force: 1.5,
                dj_jump_force: 2.17,
                weight: 85,
            },
            Character::Doc => Attributes {
                name: "Dr. Mario".to_owned(),
                index: 21,
                air_jumps: 1,
                friction: 0.06,
                size: 10,
                gravity: 0.1,
                terminal_velocity: 1.7,
                max_walk_speed: 1.1,
                fast_fall_speed: 2.3,
                air_speed: 0.9,
                air_friction: 0.02,
                air_mobility: 0.04,
                dj_x_speed: 0.87,
                fh_jump_force: 2.3,
                sh_jump_force: 1.4,
                dj_jump_force: 2.21,
                weight: 100,
            },
            Character::Mario => Attributes {
                name: "Mario".to_owned(),
                index: 0,
                air_jumps: 1,
                friction: 0.06,
                size: 10,
                gravity: 0.1,
                terminal_velocity: 1.7,
                max_walk_speed: 1.1,
                fast_fall_speed: 2.3,
                air_speed: 0.9,
                air_friction: 0.02,
                air_mobility: 0.04,
                dj_x_speed: 0.87,
                fh_jump_force: 2.3,
                sh_jump_force: 1.4,
                dj_jump_force: 2.21,
                weight: 100,
            },
            Character::Luigi => Attributes {
                name: "Luigi".to_owned(),
                index: 17,
                air_jumps: 1,
                friction: 0.03,
                size: 11,
                gravity: 0.07,
                terminal_velocity: 1.6,
                max_walk_speed: 1.1,
                fast_fall_speed: 2.0,
                air_speed: 0.68,
                air_friction: 0.01,
                air_mobility: 0.7,
                dj_x_speed: 0.89,
                fh_jump_force: 2.4,
                sh_jump_force: 1.4,
                dj_jump_force: 2.09,
                weight: 100,
            },
            Character::Link => Attributes {
                name: "Link".to_owned(),
                index: 6,
                air_jumps: 1,
                friction: 0.1,
                size: 11,
                gravity: 0.11,
                terminal_velocity: 2.13,
                max_walk_speed: 1.2,
                fast_fall_speed: 3.0,
                air_speed: 1.0,
                air_friction: 0.01,
                air_mobility: 0.06,
                dj_x_speed: 1.0,
                fh_jump_force: 2.5,
                sh_jump_force: 1.5,
                dj_jump_force: 2.09,
                weight: 104,
            },
            Character::Ylink => Attributes {
                name: "Young Link".to_owned(),
                index: 20,
                air_jumps: 1,
                friction: 0.08,
                size: 10,
                gravity: 0.11,
                terminal_velocity: 2.13,
                max_walk_speed: 1.2,
                fast_fall_speed: 2.2,
                air_speed: 1.0,
                air_friction: 0.01,
                air_mobility: 0.06,
                dj_x_speed: 1.0,
                fh_jump_force: 2.62,
                sh_jump_force: 1.5,
                dj_jump_force: 2.2,
                weight: 85,
            },
            Character::DK => Attributes {
                name: "Donkey Kong".to_owned(),
                index: 3,
                air_jumps: 1,
                friction: 0.08,
                size: 16,
                gravity: 0.11,
                terminal_velocity: 2.13,
                max_walk_speed: 1.2,
                fast_fall_speed: 2.96,
                air_speed: 1.0,
                air_friction: 0.02,
                air_mobility: 0.04,
                dj_x_speed: 1.0,
                fh_jump_force: 2.7,
                sh_jump_force: 1.6,
                dj_jump_force: 2.36,
                weight: 114,
            },
            Character::Bowser => Attributes {
                name: "Bowser".to_owned(),
                index: 5,
                air_jumps: 1,
                friction: 0.06,
                size: 16,
                gravity: 0.13,
                terminal_velocity: 1.9,
                max_walk_speed: 0.65,
                fast_fall_speed: 2.4,
                air_speed: 0.8,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 0.89,
                fh_jump_force: 2.8,
                sh_jump_force: 1.6,
                dj_jump_force: 2.67,
                weight: 117,
            },
            Character::GNW => Attributes {
                name: "Game and Watch".to_owned(),
                index: 24,
                air_jumps: 1,
                friction: 0.06,
                size: 10,
                gravity: 0.1,
                terminal_velocity: 1.7,
                max_walk_speed: 1.1,
                fast_fall_speed: 2.3,
                air_speed: 1.0,
                air_friction: 0.02,
                air_mobility: 0.05,
                dj_x_speed: 0.95,
                fh_jump_force: 2.3,
                sh_jump_force: 1.4,
                dj_jump_force: 2.21,
                weight: 60,
            },
            Character::Popo => Attributes {
                name: "Popo".to_owned(),
                index: 10,
                air_jumps: 1,
                friction: 0.04,
                size: 10,
                gravity: 0.1,
                terminal_velocity: 1.6,
                max_walk_speed: 0.95,
                fast_fall_speed: 2.0,
                air_speed: 0.7,
                air_friction: 0.02,
                air_mobility: 0.05,
                dj_x_speed: 0.88,
                fh_jump_force: 2.6,
                sh_jump_force: 1.4,
                dj_jump_force: 2.5,
                weight: 88,
            },
            Character::Nana => Attributes {
                name: "Nana".to_owned(),
                index: 11,
                air_jumps: 1,
                friction: 0.04,
                size: 10,
                gravity: 0.1,
                terminal_velocity: 1.6,
                max_walk_speed: 0.95,
                fast_fall_speed: 2.0,
                air_speed: 0.7,
                air_friction: 0.02,
                air_mobility: 0.05,
                dj_x_speed: 0.88,
                fh_jump_force: 2.6,
                sh_jump_force: 1.4,
                dj_jump_force: 2.5,
                weight: 88,
            },
            Character::Kirby => Attributes {
                name: "Kirby".to_owned(),
                index: 4,
                air_jumps: 5,
                friction: 0.08,
                size: 9,
                gravity: 0.08,
                terminal_velocity: 1.6,
                max_walk_speed: 0.85,
                fast_fall_speed: 2.0,
                air_speed: 0.78,
                air_friction: 0.02,
                air_mobility: 0.06,
                dj_x_speed: 0.53,
                fh_jump_force: 2.0,
                sh_jump_force: 1.5,
                dj_jump_force: 1.92,
                weight: 70,
            },
            Character::Mewtwo => Attributes {
                name: "Mewtwo".to_owned(),
                index: 16,
                air_jumps: 1,
                friction: 0.04,
                size: 15,
                gravity: 0.08,
                terminal_velocity: 1.5,
                max_walk_speed: 1.0,
                fast_fall_speed: 2.3,
                air_speed: 1.2,
                air_friction: 0.02,
                air_mobility: 0.05,
                dj_x_speed: 0.95,
                fh_jump_force: 2.3,
                sh_jump_force: 1.4,
                dj_jump_force: 0.0,
                weight: 85,
            },
            Character::Ness => Attributes {
                name: "Ness".to_owned(),
                index: 8,
                air_jumps: 1,
                friction: 0.06,
                size: 10,
                gravity: 0.09,
                terminal_velocity: 1.83,
                max_walk_speed: 0.84,
                fast_fall_speed: 2.2,
                air_speed: 0.93,
                air_friction: 0.03,
                air_mobility: 0.06,
                dj_x_speed: 0.6,
                fh_jump_force: 2.5,
                sh_jump_force: 1.5,
                dj_jump_force: 0.0,
                weight: 94,
            },
            Character::Pichu => Attributes {
                name: "Pichu".to_owned(),
                index: 23,
                air_jumps: 1,
                friction: 0.1,
                size: 9,
                gravity: 0.11,
                terminal_velocity: 1.9,
                max_walk_speed: 1.24,
                fast_fall_speed: 2.5,
                air_speed: 0.85,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 0.85,
                fh_jump_force: 2.6,
                sh_jump_force: 1.7,
                dj_jump_force: 2.49,
                weight: 55,
            },
            Character::Yoshi => Attributes {
                name: "Yoshi".to_owned(),
                index: 14,
                air_jumps: 1,
                friction: 0.06,
                size: 11,
                gravity: 0.09,
                terminal_velocity: 1.93,
                max_walk_speed: 1.15,
                fast_fall_speed: 2.93,
                air_speed: 1.2,
                air_friction: 0.01,
                air_mobility: 0.05,
                dj_x_speed: 1.2,
                fh_jump_force: 2.5,
                sh_jump_force: 1.8,
                dj_jump_force: 0.0,
                weight: 108,
            },
            Character::Zelda => Attributes {
                name: "Zelda".to_owned(),
                index: 19,
                air_jumps: 1,
                friction: 0.1,
                size: 11,
                gravity: 0.07,
                terminal_velocity: 1.4,
                max_walk_speed: 0.7,
                fast_fall_speed: 1.85,
                air_speed: 0.95,
                air_friction: 0.05,
                air_mobility: 0.05,
                dj_x_speed: 0.95,
                fh_jump_force: 2.1,
                sh_jump_force: 1.6,
                dj_jump_force: 1.73,
                weight: 90,
            },
        }
    }
}
